### ISSUE TITLE
Set env variables silently?

### ISSUE THREAD

**Issue by lynnrinkui** [gurinderhans/threefingerdrag#1]
Very nice work! Finally found something that works smoothly on my bootcamp!
I have a question though, is there a way to let the app remember the env variables I set before, or to run the powershell script command silently without showing the blue command line window?

**Comment by gurinderhans** [comment]
Thank you!

And yes you can, but you'll have to use vbscript..

Create a file called `tfd.vbs` with below contents (_adjust values accordingly_):
```
Set shell = CreateObject("WScript.Shell")
Set env = shell.Environment("process")

env("DragSpeedMultiplier")=1.1
env("ThreeFingerMaxDistApartMultiplier")=2.5

shell.Run "C:\pathTo\tfd.exe"
```

If you run this, it wont create any visible window.

You can go further to auto start it on computer boot, by using windows "Task Scheduler" and create a task to run this script on boot :)


Alternatively, you should be able to set these vars in "User variables for" in your environment variables:
<img src="https://user-images.githubusercontent.com/3400083/205429364-0e11957d-1124-470f-a674-e2287c164619.png" width="500" />

And then the `.exe` should auto pickup these values.
